In [2]:
# ! pip install numpy 

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 7.4 MB/s eta 0:00:00 MB/s eta 0:00:010:01


# NumPy

# 1. 넘파이 개요

## 1.1 넘파이 배열 생성해보기 

In [5]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(type(arr))


<class 'numpy.ndarray'>


In [6]:
arr2 = np.eye(3)
print(type(arr2))
arr2

<class 'numpy.ndarray'>


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr3 = np.eye(3, 5) # 3행5열, 2차원
print(type(arr3))
arr3

<class 'numpy.ndarray'>


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

## 1.2 행렬 합 연산 비교 

In [11]:
matrix_01 = [[1,2], [3,4]]
matrix_02 = [[5,6], [7,8]]

In [12]:
# litS
matrix_result = []

for i in range(len(matrix_01)):
    tmp = []
    for j in range(len(matrix_02)):
        tmp.append(matrix_01[i][j] + matrix_02[i][j])
    
    matrix_result.append(tmp)

print(matrix_result)


[[6, 8], [10, 12]]


In [13]:

# numpy 게산
matrix_result = np.array(matrix_01) + np.array(matrix_02)
matrix_result

array([[ 6,  8],
       [10, 12]])

# 2. 배열생성 1

## 2.1 배열 생성 

In [14]:
import numpy as np 
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

## 2.2 배열 모양 확인

In [15]:
arr.shape

(5,)

## 2.3 type 확인 

In [16]:
print(type(arr))

<class 'numpy.ndarray'>


## 2.4 모든 요소가 같은 자료형

In [18]:
arr_2 = np.array([0.1, 3, 5, 18, 0.8])

print(arr_2.dtype)
arr_2

float64


array([ 0.1,  3. ,  5. , 18. ,  0.8])

In [19]:
print(arr.dtype)

int64


## 2.5 무한대 표현과 정의할 수 없는 숫자 표현 

- 무한대 표현: np.inf (infinity)
- 정의할 수 없는 숫자: np.nan (not a number)
- 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf가 나옴
- 0을 0으로 나누려고 시도하면 np.nan이 나옴


In [20]:
np.array([0, 1, -1, 0]) / np.array([1,0,0,0])

/var/folders/ly/q95qq9b15wq_cmvm_6tyh_1h0000gn/T/ipykernel_52952/2764667070.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1,0,0,0])
/var/folders/ly/q95qq9b15wq_cmvm_6tyh_1h0000gn/T/ipykernel_52952/2764667070.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

## 2.6 2차원 배열 생성

In [22]:
arr = np.array([[0,1,2], [3,4,5]])

print(len(arr)) # 행 개수
print(len(arr[0])) # 열 개수
print(arr.shape) # 배열의 크기


2
3
(2, 3)


## 2.7 3차원 배열 생성

In [23]:
arr = np.array([[[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]],
                 [[13,14,15,16],
                  [17,18,19,20],
                  [21,22,23,24]]])

In [24]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [26]:
print(arr.shape) # 크기 - (깊이, 행, 열)
print(arr.ndim) # 차원 - 3차원
print(arr.dtype) # 요소의 자료형

(2, 3, 4)
3
int64


## 2.8 배열의 차원과 크기 알아내기 

## 2.9 배열생성 실습 01

[문제] 넘파이를 사용하여 다음과 같은 행렬을 만들어 보세요

[실행 결과] 
```
array([[10, 20, 30, 40],
    [50, 60, 70, 80]])
```

In [ ]:
import numpy as np
# arr = np.array([[10,20,30,40], [50,60,70,80]])
arr = np.array([[_ for _ in range(10, 41, 10)],
                [_ for _ in range(50, 81, 10)]]) # 리스트 컴프리헨션 _ 어떠한 목적으로 사용되지 않을경우 사용
# for _ in range(3):
#     print(_)  그냥 안쓰는거 아무런 동작을 하지 않는다는거지

arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 2.10 배열생성 실습 02

[문제]
- 1~18의 값을 가지는 shape이 (3, 2, 3) ndarray를 만들어 봅시다.
- 단, 자료형은 실수로 합니다. 

[실행 결과]
```
array([[[1., 2., 3.],
    [4., 5., 6.,]],
    [[7., 8., 9.,],
        [10., 11., 12.]],
    [[13., 14., 15.],
        [16., 17., 18.]]])
```

In [31]:
arr_1 = np.array([[[1.,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(arr_1.shape)
print(arr_1)

(3, 2, 3)
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[13. 14. 15.]
  [16. 17. 18.]]]


In [ ]:
data = []
# (3,2,3) 3번도는 for문안에 2번도는 for문안에 3번도는 for문

for i in range(3):
    group = []
    for j in range(2):
        row = []
        for k in range(3):
            value = float(k + j*3 + i*6 + 1) # 0+0+0+1 -> 1+0+0+1 -> 2+0+0+1 | 0+3+0+1 -> 1+3+0+1 -> 2+3+0+1

            row.append(value)
        group.append(row)
    data.append(group)
print(data)


[[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]], [[13.0, 14.0, 15.0], [16.0, 17.0, 18.0]]]


### 계산 구조와 규칙
(3,2,3) 3번도는 for문안에 2번도는 for문안에 3번도는 for문

| **구조**       | **행/열/그룹**          | **계산**        |
|-----------------|-------------------------|-----------------|
| **1 행**       | 열별 값 증가            | `k + 1`         |
| **1 그룹**     | 행별 값 증가            | `j * 3`         |
| **전체 구조**  | 그룹별 값 증가          | `i * 6`         |


In [34]:
result = np.array(data)
result

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]])

# 3. 벡터화 연산 

## 3.1 벡터화 연산

In [35]:
data = [0,1,2,3,4,5,6,7,8,9]

answer = [2*d for d in data]
answer


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [36]:
answer = np.array(data) * 2 # 배열로 만들고 * 처리
answer

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(2 * a + b)
c = 2 * a + b
type(c)

[12 24 36]


numpy.ndarray

In [41]:
print(a == 2)
print(type(a == 2))


[False  True False]
<class 'numpy.ndarray'>


## 3.2 벡터화 연산 실습 01

[문제] \
array([[1, 2, 3], [4, 5, 6]])과 array([[7, 8, 9], [10, 11, 12]])를 만들고 이 두 넘파이 배열을 활용하여아래의 계산 결과를 구해보세요.


In [48]:
arr_100 = np.array([[_ for _ in range(1,4)], [_ for _ in range(4,7)]])
arr_200 = np.array([[_ for _ in range(7,10)],[_ for _ in range(10,13)]])

In [49]:
print(arr_100)
print(arr_200)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [50]:
arr_300 = arr_100 + arr_200
print(arr_300)

[[ 8 10 12]
 [14 16 18]]


## 3.3 벡터화 연산 실습 02

[문제]  
- 1부터 9까지 정수 값을 갖는 1차원 ndarray를 생성하세요.
- 그리고 그 ndarray를 활용항 3부터 27까지의 3배수를 갖는 ndarray를 출력해보세요.


In [54]:
arr_1 = np.array([_ for _ in range(1, 10)])
arr_2 = arr_1 * 3
arr_2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

# 4. 배열의 인덱싱과 슬라이싱 

In [55]:
import numpy as np

In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

b = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

In [57]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [60]:
print(a, b, sep='\n\n')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [61]:
display(a)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

## 4.1 print와 display 차이 살펴보기

In [ ]:
display('안녕\n하세요') # 표활용시 좋음, 구조화된 데이터 보기 좋음
print('안녕\n하세요')

'안녕\n하세요'

안녕
하세요


In [64]:
! pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 11.5 MB/s eta 0:00:00MB/s eta 0:00:01:01


In [65]:
import pandas as pd

# 간단한 DataFrame 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)

# DataFrame 출력
print(df)
df
display(df)
# df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Diana   28      Houston


Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Diana   28      Houston

## 4.2 배열의 인덱싱

### 4.2.1 1차원 배열 인덱싱

### 4.2.2 다차원 배열 인덱싱

1. 2차원 배열

In [69]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]])
print(a[1,2])
print(a[0,1])
print(a[1,1])
print(a[1][1])

6
2
5
5


In [71]:
print(a[-1,-1]) # 마지막 행의 마지막 열
print(a[-1][-1])

6
6


2. 3차원 배열

In [72]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
	[[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

In [76]:
print(a[0,2])
print(a[0][2])
a[0,2]

[7 8 9]
[7 8 9]


array([7, 8, 9])

In [79]:
print(a[0, 2, 0])
print(a[1,1,2])
print(a[1][1][2])

7
60
60


## 4.3 배열 슬라이싱

1. 2차원 배열 슬라이싱

In [80]:
a = np.array([[0, 1, 2], [3, 4, 5]])
display(a)

array([[0, 1, 2],
       [3, 4, 5]])

In [86]:
print(a[1, :])
print(a[:, 2])
print(a[:, -1]) # a[0][-1], a[1][-1]
print(a[1, 1:])

[3 4 5]
[2 5]
[2 5]
[4 5]


2. 3차원 배열 슬라이싱

In [87]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
	[[10, 20, 30], [40, 50, 60], [70, 80, 90]]])
display(a)
print(a.shape)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

(2, 3, 3)


In [89]:
print(a[:, -1])
print(a[:, 2])

[[ 7  8  9]
 [70 80 90]]
[[ 7  8  9]
 [70 80 90]]


In [90]:
print(a[:, 1:])

[[[ 4  5  6]
  [ 7  8  9]]

 [[40 50 60]
  [70 80 90]]]


3. 증감을 표현하는 슬라이싱

In [91]:
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [94]:
print(a[:,::2])

[[[ 1  2  3]
  [ 7  8  9]]

 [[10 20 30]
  [70 80 90]]]


## 4.4 슬라이싱 실습 01

[문제] 주어진 행렬에 대하여 각 문제를 해결해보세요.
- 값 7 인덱싱
- 값 14 인덱싱
- 배열 [6, 7] 슬라이싱
- 배열 [7, 12] 슬라이싱
- 배열 [[3, 4], [8, 9]]


## 4.5 슬라이싱 실습 02

[문제] 주어진 행렬에 대하여 각 문제를 해결해보세요.
\
\
array([[[  1,   2,   3], \
        [  4,   5,   6], \
        [  7,   8,   9]], \
 \
       [[ 10,  20,  30], \
        [ 40,  50,  60], \
        [ 70,  80,  90]], \
\
       [[100, 200, 300], \
        [400, 500, 600], \
        [700, 800, 900]]])
        

## 02 배열 생성

In [95]:
# 0의 값을 가진 배열 생성, default=float
# np.zeros((shape, dtype='type'))
# type = i = int

c = np.zeros((5,2))
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [96]:
c.dtype

dtype('float64')

In [97]:
c.shape

(5, 2)

In [99]:
c_ = np.zeros((5,2), dtype='i')
c_

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [ ]:
# 1의 값을 가진 배열 생성
# np.ones((shape), dtype='type')

In [ ]:
# zeros_like(array, dtype='type')
# np.ones_like(array, dtype='type')

## 02-1

[문제 1] 아래와 같은 배열을 출력하세요
\
\
array([[2, 5, 8], \
    [20, 50, 80], \
    [200, 500, 800]])


## 02-2

[문제 2] 아래와 같은 배열을 출력하세요
\
\
array([[1, 3], \
    [100, 300]])


## 02-3

[문제 2] 아래와 같은 배열을 출력하세요
\
\
array([[[3, 2, 1], \
    [9, 8, 7]], \
\
    [[30, 20, 10], \
    [90, 80, 70]]])


# 5. 배열생성 2

## 5.1 zeros

## 5.2 ones

In [103]:
e = np.ones((2,3,4), dtype='i')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [101]:
e.shape

(2, 3, 4)

In [104]:
e.dtype

dtype('int32')

## 5.3 zeros_like, ones_like

## 배열생성2 실습 01

[문제] 빈 문자열을 갖는 shape이 (3, 3, 3) ndarray를 만들어 봅시다.
- 단, dtype은 ‘U10’으로 합니다.


## 배열생성2 실습 02
[문제] zeros/ones 함수를 사용해서 배열을 만들고 아래와 같은 배열을 만들어 보세요
\
\
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 배열생성2 실습 03
[문제] zeros/ones 함수를 사용해서 배열을 만들고 아래와 같은 배열을 만들어 보세요


## 5.4 empty

In [110]:
# 재활용

h = np.empty((4,3))
h

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 5.5 arange

In [105]:
# range와 동일한 역할 (시작, 끝, 증감)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

## 5.6 random

In [ ]:
# 난수 생성
# random.rand(size) / random.randint(start, end, size), .randn(size)

In [ ]:
# random.rand(size): 0~1 난수 생성
print(np.random.rand(3,3))

[[0.39784898 0.78029694 0.41344195]
 [0.62401042 0.1717577  0.30584477]
 [0.88973165 0.88181093 0.36593089]]


In [113]:
# random.random(size): 0~1 난수 생성
# size를 튜플로 전달
print(np.random.random((3,3)))

[[0.34833076 0.33989617 0.78055309]
 [0.00099856 0.03601536 0.42849738]
 [0.11095896 0.82731906 0.17931946]]


In [114]:
# random.randint(start, end, (size))
print(np.random.randint(1,10,(2,3)))

[[8 1 4]
 [2 2 5]]


In [115]:
# random.randn(size): 정규분포 따름
print(np.random.randn(3,4))

[[-0.67978836 -1.25405242 -0.09194727 -0.30978374]
 [-0.911415   -1.32348037 -1.19699092 -1.34900622]
 [-0.12151904 -0.24516679 -0.84915059  1.27076176]]


## 5.7 linspace, logspace

In [5]:
import numpy as np

arr = np.linspace(0, 100, 5) # 0~100 구간에서 5개로 쪼갠 요소를 선택해서 배열을 만들겠다.
arr 

array([  0.,  25.,  50.,  75., 100.])

In [6]:
arr = np.logspace(0, 100, 5) # 0~100 구간에서 5개로 쪼갠 요소를 선택해서 배열을 만들겠다.
arr

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

## 배열생성2 실습 04

[문제] linspace()를 활용하여 다음과 같은 1차원 ndarray를 만들어 보세요
\
\
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [10]:
arr = np.linspace(0.1, 0.9, 9)
arr

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

# 6. 배열 크기 변경

넘파이에서의 메타데이터와 데이터 버퍼

- 메타데이터: 데이터 자체를 변경하지 않고도, 데이터의 표현 방식 수정 가능
    - 데이터 형태: shape
    - dtype 
    - strides: 배열의 각 차원이 메모리에서 얼마나 떨어져있는지 (바이트 단위)
    - 메모리 읽기/쓰기 플래그: 배열이 읽기 전용인지 여부
    - 배열의 순서: 배열이 C-order(행 우선)인지 F-order(열 우선)인지 여부
    - 배열 객체 ID: 파이썬 수준에서 배열 객체를 구분하는 고유 메모리 주소 
- 데이터 버퍼 (Data Buffer)
    - 데이터 자체가 저장된 메모리 공간을 의미 (배열의 요소 값들이 연속적으로 저장됨)
        - 배열 데이터가 저장된 연속적인 메모리 블록의 시작 주소를 의미
    - NumPy 배열은 데이터를 C언어에서 사용하는 연속된 메모리 블록에 저장
    - __ array_interface __ ['data']를 통해 데이터 버퍼의 메모리 주소 확인 가능 
    - 버퍼에는 배열의 실제 데이터 값이 저장됨 
    - 특징
        - 배열의 요소는 데이터 버퍼에 저장 됨 (arr[0][0]은 버퍼의 특정 메모리 주소를 참조)
        - 데이터 공유: 뷰(view)배열은 원본 배열과 동일한 데이터 버퍼를 참조 -> 데이터 공유 가능 
        - 데이터는 일반적으로 연속적인 메모리 공간에 저장되며, strides를 통해 각 차원의 데이터 간 간격을 결정 

id와 __ array_interface __

- id()
    - 파이썬 자체의 고유 메모리 주소 반환
    - 객체의 컨테이너 또는 참조 수준에서 메모리 주소 확인 
    - 객체의 내부 데이터가 아닌 객체 자체에 대한 정보 제공
    - 객체가 같은 데이터를 공유하더라도 다른 ID를 가질 수 있음 (Numpy 배열에서 뷰(view)와 원본 배열의 경우)
    - arr과 view_arr의 id는 다름. 이는 배열의 메타데이터와 배열 객체가 독립적으로 존재하기 때문 

- __ array_interface __
    - Numpy 배열 객체가 관리하는 실제 데이터 버퍼의 정보 제공 
    - 데이터 버퍼 주소를 확인하는 데 유용하며, 원본 배열과 뷰(view)간에 데이터 공유 여부를 판단할 수 있음 
        - 두 배열의 데이터 버퍼 주소가 같다면, 같은 메모리를 참조하고 있음을 의미 
    - Numpy 배열의 내부 구조를 설명하는 속성 (attribute) -> 이 속성을 통해 배열의 데이터 버퍼 주소, dtype, strides 등을 알 수 있음 
    - 딕셔너리 형태이며 주요키는 아래와 같음
        - data: 배열이 참조하는 데이터 버퍼의 메모리 주소와 읽기/쓰기 플래그 반환
            - 읽기 쓰기 플래그: False(읽기 전용), True(읽기 쓰기 모두 가능) -> 하지만 객체수준에서만 적용됨 (데이터 버퍼는 해당 안 됨)
        - shape: 배열의 형태
        - strides: 데이터가 메모리에서 이동하는 간격 (바이트단위)
        - typestr: 배열의 데이터 타입 (dtype)
        - version: 인터페이스 버전 
    

## 6.1 reshape

In [ ]:
import numpy as np

a = np.arange(12)
print(id(a))
print(a.__array_interface__) 
# 'data': (5410136112, False) - 첫번째 공간의 참조주소, 쓰기전용



4571107792
{'data': (5410136112, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (12,), 'version': 3}


In [13]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(id(a.reshape(3,4)))
print(a.reshape(3,4).__array_interface__['data'][0]) # '0' 요소의 시작주소 # 뷰배열

4571215408
5410136112


In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a_re = a.reshape(3,4)

# 배열 확인
print(a)
print(a_re)
print()

# 각 객체의 id 주소 확인
print(id(a))
print(id(a_re))
print()

# reshape 객체의 base(원본) 확인
print(a_re.base) # 어떤 원본을 참조하고 있는가?
print()

# 데이터 범퍼 주소 확인
print(a.__array_interface__['data'][0])
print(a_re.__array_interface__['data'][0])
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

4571107792
4572049840

[ 0  1  2  3  4  5  6  7  8  9 10 11]

5410136112
5410136112



In [22]:
# -1을 활용한 배열변경

test = a.reshape(3, -1)
test


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
test.shape

(3, 4)

In [24]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [25]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [26]:
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 6.2 배열크기변경 실습 01

[문제] \
1부터 40가지의 짝수를 갖는 ndarray를 arange()로 만듭니다.\
그리고 shape을 변경하여 (2, 2, 5)로 변경해보세요.\
\
[2 4 6 8 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40] \
\
[결과] \
array([[[2, 4, 6, 8, 10], \
    [12, 14, 16, 18, 20], \
\
    [[22, 24, 26, 28, 30], \
    [32, 34, 36, 38, 40]]])



In [28]:
import numpy as np

arr = np.arange(2, 41, 2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [29]:
arr.reshape(2,2,5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

## 6.3 flatten, ravel

### 6.3.1 flatten
- 깊은 복사

In [37]:
# (3,4)
a = np.array([[0,1,2,3],
              [4,5,6,7,],
              [8,9,10,11]])
a = np.arange(12)
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a_flatten = a.flatten()

print(a_flatten.shape)
a_flatten

(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# a의 첫 번째 요소의 ID
print(a[0][0])
print(id(a[0][0])) # id - 객체주소
print(a.__array_interface__['data']) # 데이터 버퍼
print()

# flattne의 첫 번째 요소 ID  # 깊은 복사이므로 데이터 버퍼의 주소는 달라진다. 
print(a_flatten[0])
print(id(a_flatten[0]))
print(a_flatten.__array_interface__['data']) # 데이터 버퍼

0
4571771952
(5410065280, False)

0
4571771952
(4347305488, False)


In [ ]:
# 요소 변경 -> 두 객체가 다 변경이 되지 않음(깊은 복사라서)
print(a_flatten[0])
a_flatten[0] = 100
print()

# 변경된 array 확인
print(a)
print()
print(a_flatten) # 시작하는 메모리 주소가 다르기때문에 서로 영향을 주지 않은것 

0

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[100   1   2   3   4   5   6   7   8   9  10  11]


### 6.3.2 ravel
- 얕은 복사

In [42]:
a = np.array([[0,1,2,3],
              [4,5,6,7,],
              [8,9,10,11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a_ravel = a.ravel()
a_ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
# id
print(id(a))
print(id(a_ravel))
print()

# 0번째 요소 id
print(id(a[0][0]))
print(id(a_ravel[0]))
print()

# 버퍼
print(a.__array_interface__['data'])
print(a_ravel.__array_interface__['data'])

4572146032
4574198352

4571773264
4571763728

(5410211040, False)
(5410211040, False)


In [ ]:
# 0번째 요소 100으로 변경
# 변경 전 값 확인

print(id(a[0][0]))
print(id(a_ravel[0]))
print(a.__array_interface__['data'])
print(a_ravel.__array_interface__['data'])
print()

# 요소변경
a_ravel[0] = 100

# 변경 후 값 확인
print(a)
print(a_ravel) # 뷰배열 - 원본을 참조하고 있는 배열

print(a_ravel.base)

4571760848
4571772944
(4340041232, False)
(4340041232, False)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[100   1   2   3   4   5   6   7   8   9  10  11]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


---
예제

In [ ]:
# ravel
import numpy as np

# 원본 배열 생성
arr = np.array([[1,2],[3,4]])

# arr의 뷰(view) 생성
arr_view = arr.ravel()

# 뷰를 수정하면 원본도 변경됨
arr_view[0] = 99

print(arr)
print(arr_view)
print()

print(id(arr))
print(id(arr_view))
print(id(arr[0]))
print(id(arr_view[0]))
print()

# 실제 데이터 주소 비교(데이터 버퍼 비교)
print(arr.__array_interface__['data'][0])
print(arr_view.__array_interface__['data'][0])

[[99  2]
 [ 3  4]]
[99  2  3  4]

4573950096
4573952016
4574426672
4574447568

4339833344
4339833344


In [ ]:
import numpy as np

# 원본 배열 생성
arr = np.array([[1,2],[3,4]])

# flatten()
arr_2 = arr.flatten()

# flatten() 배열 수정해도 원본은 변경되지 않음
arr_2[0] = 99

print(arr)
print(arr_2)
print()

print(id(arr))
print(id(arr_2))
print(id(arr[0]))
print(id(arr_2[0]))
print()

# 실제 데이터 주소 비교(데이터 버퍼 비교) - 버퍼주소가 다름
print(arr.__array_interface__['data'][0])
print(arr_2.__array_interface__['data'][0])

[[1 2]
 [3 4]]
[99  2  3  4]

4574422544
4574663696
4574665136
4574448240

4604916512
4357027504


## 6.4 newaxis
- 인덱싱 기법으로 배열의 차원을 늘리는 데 유용

In [53]:
# 1차원 배열 생성
a = np.arange(12)

print(a.shape, a.ndim)

a

(12,) 1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
# 차원 증가
a = a[:, np.newaxis] # 행 다 선택, 새로운 축 추가 -> 모든 행은 유지하면서 새로운 열을 추가

print(a.shape, a.ndim)

a


(12, 1) 2


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

## 6.5 전치 

In [55]:
a = np.array([[1,2,3], [4,5,6]])

print(a.shape, a.ndim)
a

(2, 3) 2


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 전치 - 행과열을 바꿈
b = a.T # (2,3)-> (3,2)

print(b.shape, b.ndim)
b

(3, 2) 2


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
print(id(a))
print(id(b))

print()

print(a.__array_interface__['data'][0]) # 시작주소가 같으므로 변경시 동시변경된다. 실제 데이터(요소)의 위치는 동일
print(b.__array_interface__['data'][0]) # 연속적으로 저장이 되기 때문에 

4572151120
4574186832

5410202624
5410202624


In [58]:
b[0][0] = 100

print(a)
print(b)

[[100   2   3]
 [  4   5   6]]
[[100   4]
 [  2   5]
 [  3   6]]


## 6.6 배열 결합

### 6.6.1 hstack
배열을 수평으로 연결 

In [59]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60]])

print(a.shape)
print(b.shape)
print()
print(a)
print(b)

(2, 3)
(2, 3)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]


In [62]:
c_hstack = np.hstack([a, b])
print(c_hstack.shape)
print()
c_hstack

(2, 6)



array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

### 6.6.2 vstack
배열을 수직으로 연결 

In [63]:
c_vstack = np.vstack([a, b])
print(c_vstack.shape)
print()
c_vstack

(4, 3)



array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

# 7. 브로드캐스팅

In [ ]:
import numpy as np

a = np.array([1,2,3]) # 1차원 (3,)
b = np.array([[10], [20], [30]]) # 2차원 인데 요소가 하나씩만 (3,1)

print(a.shape)
print(b.shape)

# 1. 차원이 맞는지 확인
# 2. 차원의 크기가 하나라도 1이여야

(3,)
(3, 1)


In [ ]:
result = a + b
print(result.shape)
result

# a 가 b 에 맞춰서 확장
# (1, 3) + (3, 1) -> (3, 3)
# [[1,2,3]] + [[10],[20],[30]]

(3, 3)


array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
c = a * b
print(c.shape)
c

# a 가 b 에 맞춰서 확장
# (1, 3) * (3, 1) -> (3, 3)
# [[1,2,3]] * [[10],[20],[30]]

(3, 3)


array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [67]:
a = np.array([[1,2,3], [4,5,6]]) # 2차원
b = np.array([10,20,30]) # 1차원

print(a.shape)
print(b.shape)

(2, 3)
(3,)


In [68]:
result = a * b
print(result.shape)
result

# b 가 a 맞춰 확장
# 

(2, 3)


array([[ 10,  40,  90],
       [ 40, 100, 180]])

# 8. NumPy의 다양한 메서드 

In [69]:
a = np.array([[1,2,3], [4,5,6]]) # 2차원

## 8.1 최대/최소

In [71]:
# 최대
print(a.max())

# 최소
print(a.min())


print(a.argmax())

print(a.argmin())

6
1
5
0


## 8.1.1 argmax, argmin
- argmax: 해당 배열의 제일 큰 값의 인덱스 반환
- argmin: 해당 배열의 제일 작은 값의 인덱스 반환 

In [ ]:
arr = np.reshape(np.random.randint(100, size=(12)), (2,3,-2))
display(arr)

# 축을 설정하지 안으면 1차원으로 생가

In [ ]:
# 츅 솔종
np.random.seed(1)


arr  = np.reshape(np.rnadom.rande)

In [73]:
print(np.argmax(arr, axis=0))# (3,2,2)
print(np.argmax(arr, axis=1))
print(np.argmax(arr, axis=2))

[1 1]
[1 1]


AxisError: axis 2 is out of bounds for array of dimension 2

In [ ]:
a = np.array([])

## 8.2 통계

In [ ]:
# 합
print(a.sum()) # 배열의 메소드
print(np.sum(a)) # Numpy 메소드 - 요소의 합

21
21


In [76]:
# 평균
print(a.mean())
print(np.mean(a))

3.5
3.5


In [77]:
# 중의값
# print(a.median()) # 배열에는 없음
print(np.median(a))

3.5


In [78]:
# 표준편차
print(a.std())
print(np.std(a))

1.707825127659933
1.707825127659933


In [79]:
# 분산
print(a.var())
print(np.var(a))

2.9166666666666665
2.9166666666666665


In [80]:
a

array([[1, 2, 3],
       [4, 5, 6]])

## 8.3 불리언

### 8.3.1 all()

In [81]:
# numpy에서의 all()은 python의 and와 동일한 논리

a = np.array([True, True, True])
b = np.array([True, True, False])
c = np.array([False, False, False])

print(a.all())
print(b.all())
print(c.all())

True
False
False


In [88]:
a = np.zeros(3, dtype=int)
b = np.ones(3, dtype=int)
c = np.array([1,1,0])

print(a)
print(b)
print(c)
print()
print(a.all())
print(b.all())
print(c.all())

[0 0 0]
[1 1 1]
[1 1 0]

False
True
False


In [85]:
test = a.all()
test

np.False_

### 8.3.2 any()

In [89]:
# or과 같은 논리
a = np.array([True, True, True])
b = np.array([True, True, False])
c = np.array([False, False, False])

print(a.any())
print(b.any())
print(c.any())

True
True
False


In [ ]:
a = np.zeros(3, dtype=int)
b = np.ones(3, dtype=int)
c = np.array([1,1,0])

print(a)
print(b)
print(c)
print()
print(a.any())
print(b.any())
print(c.any())

[1 1 0]
[1 1 1]
[False False False]

True
True
False


## 8.4 NumPy의 다양한 메서드 실습 01

[문제] 1부터 100까지의 3의 배수를 갖는 1차원 ndarray를 생성하고 그 전체의 합을 구하세요

## 8.5 NumPy의 다양한 메서드 실습 02

[문제] 
- 서버 응답시간의 데이터가 다음과 같이 존재합니다.
- 해당 값의 단위는 ms 입니다.
- 이 때 200ms를 넘기는 값의 개수가 총 몇개인지 구해보세요


# 9. 정렬

In [90]:
np.random.seed(2)
arr = np.reshape(np.random.randint(20, size=12), (3, -1))
arr

array([[ 8, 15, 13,  8],
       [11, 18, 11,  8],
       [ 7,  2, 17, 11]])

In [ ]:
print(np.sort(arr, axis=0))
# 행
# 첫번쩨 행의 첫번째 열: 8 / 두번째 행의 첫번째 열: 11 / 세번째 행의 첫번째 열: 7


[[ 7  2 11  8]
 [ 8 15 13  8]
 [11 18 17 11]]


In [ ]:
print(np.sort(arr, axis=1))
# 열
# 첫번째 행의 첫번째 열: 8 / 첫번째 행의 두번째 열: 15 / 첫번째 행의 세번째 열: 13 / 첫번째 행의 네번째 열: 8


[[ 8  8 13 15]
 [ 8 11 11 18]
 [ 2  7 11 17]]
