In [ ]:
# ! pip install numpy 

In [4]:
import numpy as np

# NumPy

# 1. 넘파이 개요

## 1.1 넘파이 배열 생성해보기 

In [ ]:
# eye 메서드로 넘파이 행렬 생성해보기 1
arr = np.eye(3) # 단위 행렬 생성 코드 (단위 행렬: 대각선 요소가 1이고 나머지가 0인 행렬)

print(type(arr))
print(arr.shape) # (3, 3)
arr

<class 'numpy.ndarray'>
(3, 3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [189]:
# # eye 메서드로 넘파이 행렬 생성해보기 2
arr = np.eye(3, 5) # 단위 행렬 생성 코드 (단위 행렬: 대각선 요소가 1이고 나머지가 0인 행렬)

print(type(arr))
print(arr.shape) # (3, 3)
arr

<class 'numpy.ndarray'>
(3, 5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
# array 메서드로 1차원 배열 생성
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 타입 확인 
print(type(ar))
type(ar)

<class 'numpy.ndarray'>


numpy.ndarray

In [ ]:
# ar의 데이터 타입 확인 
print(ar.dtype) # int64 (정수가 64비트(8바이트)로 표현됨, 즉 64는 각 요소가 차지하는 비트수를 나타냄)

int64


## 1.2 행렬 합 연산 비교 

In [190]:
# list 계산 
matrix_1 = [[1, 2], [3, 4]]
matrix_2 = [[5, 6], [7, 8]]

matrix_result = []

for i in range(len(matrix_1)):
    tmp = []
    for j in range(len(matrix_2)):
        tmp.append(matrix_1[i][j] + matrix_2[i][j])
    
    matrix_result.append(tmp)

print(matrix_result)

[[6, 8], [10, 12]]


In [191]:
# numpy 계산 
matrix_result = np.array(matrix_1) + np.array(matrix_2)
print(matrix_result)

[[ 6  8]
 [10 12]]


# 2. 배열생성 1

## 2.1 배열 생성 

In [3]:
# list로 넘파이 배열 생성하기 
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # 시퀀스 자료형으로 ndarray 객체 반환 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2.2 배열 모양 확인

In [6]:
arr.shape

(11,)

## 2.3 type 확인 

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


## 2.4 모든 요소가 같은 자료형

In [16]:
arr_float = np.array([0.1, 5, 4, 12, 0.5])

print(arr_float.dtype)
arr_float # 전부 실수화 됨

float64


array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [15]:
arr_int = np.array([1, 2, 3, 4])
print(arr_int.dtype)
arr_int

int64


array([1, 2, 3, 4])

## 2.5 무한대 표현과 정의할 수 없는 숫자 표현 

- 무한대 표현: np.inf (infinity)
- 정의할 수 없는 숫자: np.nan (not a number)
- 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf가 나옴
- 0을 0으로 나누려고 시도하면 np.nan이 나옴


In [17]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0]) 

/var/folders/np/0f8tqn_j13l5c_yx0hg3k67r0000gn/T/ipykernel_73619/877491688.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
/var/folders/np/0f8tqn_j13l5c_yx0hg3k67r0000gn/T/ipykernel_73619/877491688.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

## 2.6 2차원 배열 생성

In [19]:
arr = np.array([[0, 1, 2], [3, 4, 5]])

print(len(arr)) # 행 개수 구하는 법
print(len(arr[0])) # 열 개수 구하는 법 
print(arr.shape)
arr

2
3
(2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

## 2.7 3차원 배열 생성

In [23]:
arr = np.array([[[1, 2, 3, 4],
		[5, 6, 7, 8],
		[9, 10, 11, 12]],
	    [[11, 12, 13, 14],
		[15, 16, 17, 18],
		[19, 20, 21, 22]]])

In [24]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [26]:
# 깊이, 행, 열 개수 구하기 
print(arr.shape)
len(arr), len(arr[0]), len(arr[0][0])

(2, 3, 4)


(2, 3, 4)

## 2.8 배열의 차원과 크기 알아내기 

In [27]:
arr_1d = np.array([1, 2, 3])

print(arr_1d.ndim)
print(arr_1d.shape)

1
(3,)


In [28]:
arr_2d = np.array([[0, 1, 2], [3, 4, 5]])

print(arr_2d.ndim)
print(arr_2d.shape)

2
(2, 3)


## 2.9 배열생성 실습 01

[문제] 넘파이를 사용하여 다음과 같은 행렬을 만들어 보세요

[실행 결과] 
```
array([[10, 20, 30, 40],
    [50, 60, 70, 80]])
```

In [33]:
import numpy as np

np.array([[_ for _ in range(10, 41, 10)],
          [_ for _ in range(50, 81, 10)]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 2.10 배열생성 실습 02

[문제]
- 1~18의 값을 가지는 shape이 (3, 2, 3) ndarray를 만들어 봅시다.
- 단, 자료형은 실수로 합니다. 

[실행 결과]
```
array([[[1., 2., 3.],
    [4., 5., 6.,]],
    [[7., 8., 9.,],
        [10., 11., 12.]],
    [[13., 14., 15.],
        [16., 17., 18.]]])
```

In [34]:
data = []

for i in range(3):
    group = []
    for j in range(2):
        row = []
        for k in range(3):
            value = float(k + j*3  + i*6 + 1)
            row.append(value)
        group.append(row)
    data.append(group)
print(data)

result = np.array(data)
print(result)
print()
print(result.shape)

[[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]], [[13.0, 14.0, 15.0], [16.0, 17.0, 18.0]]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]

 [[13. 14. 15.]
  [16. 17. 18.]]]

(3, 2, 3)


# 3. 벡터화 연산 

## 3.1 벡터화 연산

In [ ]:
# 리스트의 각 요소에 2를 곱해야 하는 경우 
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# for문을 통해서 계산 
answer = [2*d for d in data]

print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
# 넘파이 배열의 각 요소에 2를 곱해야하는 경우 
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

x = np.array(data)

print(x*2)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# 벡터화 연산은 비교연산과 논리연산을 포함한 모든 종류의 수학 연산에 대해 적용됨 
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2 * a + b)
print(a == 2)

[12 24 36]
[False  True False]


## 3.2 벡터화 연산 실습 01

[문제] \
array([[1, 2, 3], [4, 5, 6]])과 array([[7, 8, 9], [10, 11, 12]])를 만들고 이 두 넘파이 배열을 활용하여아래의 계산 결과를 구해보세요.


In [1]:
import numpy as np 

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

a + b

[[ 8 10 12]
 [14 16 18]]


In [2]:
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

## 3.3 벡터화 연산 실습 02

[문제]  
- 1부터 9까지 정수 값을 갖는 1차원 ndarray를 생성하세요.
- 그리고 그 ndarray를 활용항 3부터 27까지의 3배수를 갖는 ndarray를 출력해보세요.


In [9]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a_1 = np.array([_ for _ in range(1,10)])

print(a, a_1, sep='\n')
a * 3

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

# 4. 배열의 인덱싱과 슬라이싱 

In [10]:
import numpy as np

## 4.1 print와 display 차이 살펴보기

In [13]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

b = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

print(a, b, sep='\n')
display(a, b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]])

In [15]:
display('안녕\n하세요')
print('안녕\n하세요')

'안녕\n하세요'

안녕
하세요


In [19]:
import pandas as pd

# 간단한 DataFrame 생성
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data)

# DataFrame 출력
print(df)
df
display(df)
# df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Diana   28      Houston


Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Diana   28      Houston

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Diana   28      Houston


## 4.2 배열의 인덱싱

### 4.2.1 1차원 배열 인덱싱

In [30]:
# 1차원 배열 인덱싱 

a = np.array([0, 1, 2, 3, 4])

print(a[2])
print(type(a[2])) # 고속 연산을 위해 넘파이만의 고유 자료형을 가짐 
a[2]

2
<class 'numpy.int64'>


np.int64(2)

In [31]:
print(a[-1])
a[-1]

4


np.int64(4)

### 4.2.2 다차원 배열 인덱싱

1. 2차원 배열

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a[1, 2]) # 두 번째 행, 세 번째 열 (넘파이 인덱싱 방식)
print(a[1][2]) # 파이썬 인덱싱 방식 (직관적이지만, 대규모 배열에서는 성능이 다소 느릴 수도 있음)
a[1, 2]

6
6


np.int64(6)

In [33]:
print(a[0, 1]) # 첫 번째 행, 두 번째 열
print(a[0][1])
a[0, 1]

2
2


np.int64(2)

In [34]:
print(a[-1, -1]) # 마지막 행, 마지막 열
print(a[-1][-1])
a[-1, -1]

6
6


np.int64(6)

2. 3차원 배열

In [40]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
	[[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

In [41]:
print(a[0, 2]) # 첫 번째 행의 마지막 열
print(a[0][2])
print(type(a[0, 2])) # 객체 타입: numpy.ndarray
a[0, 2]

[7 8 9]
[7 8 9]
<class 'numpy.ndarray'>


array([7, 8, 9])

In [42]:
print(a[0, 2, 0]) # 첫 번재 행의 마지막열의 첫 번째 열
print(a[0][2][0])
a[0, 2, 0]

7
7


np.int64(7)

In [43]:
print(a[1, 2]) # 두 번째 행의 세 번째 열 
print(a[1][2])
a[1, 2]

[70 80 90]
[70 80 90]


array([70, 80, 90])

In [45]:
print(a[1, 2, 2]) # 두 번째 행의 세 번째 열의 세 번째 열
print(a[1][2][2])
a[1][2][2]

90
90


np.int64(90)

## 4.3 배열 슬라이싱

1. 2차원 배열 슬라이싱

In [57]:
# 2차원 배열 생성

a = np.array([[0, 1, 2], [3, 4, 5]])
display(a)

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
print(a[0, :]) # 첫 번째 행, 전체 열 
print(type(a[0, :])) # 슬라이싱 결과도 ndarray
a[0, :] 

[0 1 2]
<class 'numpy.ndarray'>


array([0, 1, 2])

In [60]:
print(a[:, -1]) # a[0][1], a[1]a[1] ->  두 번째 열 전체
a[:, -1] 

[2 5]


array([2, 5])

In [61]:
print(a[1, 1:]) # a[1][1], a[1][2]
a[1, 1:] # 두 번째 행의 두 번째 열 부터 끝 열까지

[4 5]


array([4, 5])

2. 3차원 배열 슬라이싱

In [62]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
	[[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

print(a.shape)

(2, 3, 3)


In [63]:
a[0:, 2]

# a[0][2]
# a[1][2]

array([[ 7,  8,  9],
       [70, 80, 90]])

In [55]:
a[0:, 1:]

# a[0][1]
# a[0][2]
# a[1][1]
# a[1][2]

array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[40, 50, 60],
        [70, 80, 90]]])

3. 증감을 표현하는 슬라이싱

In [65]:
a = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
	[[10, 20, 30], [40, 50, 60], [70, 80, 90]]])

In [66]:
a[0:, ::2] 

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[10, 20, 30],
        [70, 80, 90]]])

## 4.4 슬라이싱 실습 01

[문제] 주어진 행렬에 대하여 각 문제를 해결해보세요.
- 값 7 인덱싱
- 값 14 인덱싱
- 배열 [6, 7] 슬라이싱
- 배열 [7, 12] 슬라이싱
- 배열 [[3, 4], [8, 9]]


In [69]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [77]:
# 1. 7 인덱싱 
print(m[1, 2])

# 2. 14 인덱싱
print(m[2, -1])

# 3. [6, 7] 슬라이싱
print(m[1, 1:3])

# 4. [7, 12] 슬라이싱
print(m[1:, 2])

# 5. [[3, 4], [8, 9]] 슬라이싱 
print(m[:2, -2:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


## 4.5 슬라이싱 실습 02

[문제] 주어진 행렬에 대하여 각 문제를 해결해보세요.
\
\
array([[[  1,   2,   3], \
        [  4,   5,   6], \
        [  7,   8,   9]], \
 \
       [[ 10,  20,  30], \
        [ 40,  50,  60], \
        [ 70,  80,  90]], \
\
       [[100, 200, 300], \
        [400, 500, 600], \
        [700, 800, 900]]])
        

## 실습 02 배열 생성

In [7]:
# 방법 1
import numpy as np

# 배열 생성
a = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 20, 30], [40, 50, 60], [70, 80, 90]],
    [[100, 200, 300], [400, 500, 600], [700, 800, 900]]
])

a

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [8]:
# 방법 2
test = np.array([[i + j for i in range(1,4)] for j in range(3)])
print(test)
print()
test2 = test*10
print(test2)
print()
test3 = test*100
print(test3)
print()
a = np.array([test, test2, test3])
a

[[1 2 3]
 [2 3 4]
 [3 4 5]]

[[10 20 30]
 [20 30 40]
 [30 40 50]]

[[100 200 300]
 [200 300 400]
 [300 400 500]]



array([[[  1,   2,   3],
        [  2,   3,   4],
        [  3,   4,   5]],

       [[ 10,  20,  30],
        [ 20,  30,  40],
        [ 30,  40,  50]],

       [[100, 200, 300],
        [200, 300, 400],
        [300, 400, 500]]])

In [9]:
print(a.shape)
print(a.dtype)

(3, 3, 3)
int64


In [100]:
# 방법 3
import numpy as np

# arange로 배열 생성
a = np.arange(1, 10).reshape(3,3) * np.array([1, 10, 100]).reshape(3, 1, 1)

print(a)

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]


## 02-1

[문제 1] 아래와 같은 배열을 출력하세요
\
\
array([[2, 5, 8], \
    [20, 50, 80], \
    [200, 500, 800]])


In [114]:
result = a[:, :, 1]
print(result)

[[  2   5   8]
 [ 20  50  80]
 [200 500 800]]


## 02-2

[문제 2] 아래와 같은 배열을 출력하세요
\
\
array([[1, 3], \
    [100, 300]])


In [115]:
result = a[::2, 0, ::2]
result

array([[  1,   3],
       [100, 300]])

## 02-3

[문제 2] 아래와 같은 배열을 출력하세요
\
\
array([[[3, 2, 1], \
    [9, 8, 7]], \
\
    [[30, 20, 10], \
    [90, 80, 70]]])


In [122]:
result = a[:2:, ::2, ::-1]
result

array([[[ 3,  2,  1],
        [ 9,  8,  7]],

       [[30, 20, 10],
        [90, 80, 70]]])

# 5. 배열생성 2

## 5.1 zeros

In [2]:
# dtype 지정 안 한 경우
import numpy as np

c = np.zeros((5, 2))
c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
print(c.shape)
print(c.dtype)

(5, 2)
float64


In [4]:
# dtype 지정한 경우

c_ = np.zeros((5, 2), dtype='i')
c_

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [5]:
print(c_.shape)
print(c_.dtype)

(5, 2)
int32


## 5.2 ones

In [6]:
e = np.ones((2, 3, 4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
print(e.shape)
print(e.dtype)

(2, 3, 4)
float64


In [1]:
e_ = np.ones((2, 3, 4), dtype='i8')
e_

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [23]:
print(e_.shape)
print(e_.dtype)

(2, 3, 4)
int64


## 5.3 zeros_like, ones_like

In [24]:
# zeros_like

f = np.zeros_like(c_)
f

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [26]:
print(c_.shape)
print(c_.dtype)
print()
print(f.shape)
print(f.dtype)

(5, 2)
int32

(5, 2)
int32


In [27]:
# ones_like

g = np.ones_like(e_)
g

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [28]:
print(e_.shape)
print(e_.dtype)
print()
print(g.shape)
print(g.dtype)

(2, 3, 4)
int64

(2, 3, 4)
int64


## 배열생성2 실습 01

[문제] 빈 문자열을 갖는 shape이 (3, 3, 3) ndarray를 만들어 봅시다.
- 단, dtype은 ‘U10’으로 합니다.


In [31]:
reuslt = np.zeros((3, 3, 3), dtype='<U10')
reuslt

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

## 배열생성2 실습 02
[문제] zeros/ones 함수를 사용해서 배열을 만들고 아래와 같은 배열을 만들어 보세요
\
\
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
my_ones = np.ones((10, 10))
my_ones[1:9, 1:9] = my_ones[1:9, 1:9] * 0 # 10번째 인덱스가 9니깐 8번인덱스까지 0.이 나오게 해야함
my_ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
my_ones.shape

(10, 10)

## 배열생성2 실습 03
[문제] zeros/ones 함수를 사용해서 배열을 만들고 아래와 같은 배열을 만들어 보세요


In [47]:
my_ones = np.ones((10, 10))
my_ones[0::2, 1::2] = my_ones[0::2, 1::2] * 0 # 10번째 인덱스가 9니깐 8번인덱스까지 0.이 나오게 해야함
my_ones[1::2, 0::2] = my_ones[1::2, 0::2] * 0
my_ones

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

## 5.4 empty

In [48]:
h = np.empty((4, 3))
h

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 5.5 arange

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

## 5.6 random

In [ ]:
# np.random.rand(size): 0~1의 균일 분포에서 난수 생성 

print(np.random.rand(3, 3))

[[0.76245704 0.61172925 0.41621923]
 [0.60867459 0.50442132 0.99458743]
 [0.45115209 0.22836936 0.33828239]]


In [62]:
# np.random.random(size): 0~1의 균일 분포에서 난수 생성 
# size를 튜플로 전달 

print(np.random.random((3, 3)))

[[0.33124121 0.10197451 0.68562082]
 [0.94938095 0.96975406 0.77657014]
 [0.26792989 0.01847137 0.27188331]]


In [ ]:
# np.random.randint(start, end, size): start~(end-1)의 균일 분포에서 정수의 난수 생성 

print(np.random.randint(1, 10, (2, 3)))

[[7 3 1]
 [6 4 6]]


In [64]:
# np.random.randn(size): 가우시안 분포를 따르는 난수 생성

print(np.random.randn(3, 3))

[[ 3.08648003  0.03600344 -0.78463651]
 [-0.78732069  1.16711175  1.26905523]
 [-0.82527944  0.36483613 -1.51956328]]


## 5.7 linspace, logspace

In [ ]:
# linspace
ex = np.linspace(0, 100, 5) # 0~100을 5개의 구간으로 나눔
ex

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
# logspace
ex2 = np.logspace(0, 100, 5) # 0~100을 5개의 구간으로 나눔
ex2 # e는 지수표기법에서 10의 거듭제곱을 의미 (a x 10^b를 aeb 또는 aE + b의 형태로 표현)

# 즉, 1.e+000은 1.0 x 10^0 = 1을 의미 

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

## 배열생성2 실습 04

[문제] linspace()를 활용하여 다음과 같은 1차원 ndarray를 만들어 보세요
\
\
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [80]:
print(np.linspace(0.1, 0.9, 9))

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


# 6. 배열 크기 변경

넘파이에서의 메타데이터와 데이터 버퍼

- 메타데이터: 데이터 자체를 변경하지 않고도, 데이터의 표현 방식 수정 가능
    - 데이터 형태: shape
    - dtype 
    - strides: 배열의 각 차원이 메모리에서 얼마나 떨어져있는지 (바이트 단위)
    - 메모리 읽기/쓰기 플래그: 배열이 읽기 전용인지 여부
    - 배열의 순서: 배열이 C-order(행 우선)인지 F-order(열 우선)인지 여부
    - 배열 객체 ID: 파이썬 수준에서 배열 객체를 구분하는 고유 메모리 주소 
- 데이터 버퍼 (Data Buffer)
    - 데이터 자체가 저장된 메모리 공간을 의미 (배열의 요소 값들이 연속적으로 저장됨)
        - 배열 데이터가 저장된 연속적인 메모리 블록의 시작 주소를 의미
    - NumPy 배열은 데이터를 C언어에서 사용하는 연속된 메모리 블록에 저장
    - __ array_interface __ ['data']를 통해 데이터 버퍼의 메모리 주소 확인 가능 
    - 버퍼에는 배열의 실제 데이터 값이 저장됨 
    - 특징
        - 배열의 요소는 데이터 버퍼에 저장 됨 (arr[0][0]은 버퍼의 특정 메모리 주소를 참조)
        - 데이터 공유: 뷰(view)배열은 원본 배열과 동일한 데이터 버퍼를 참조 -> 데이터 공유 가능 
        - 데이터는 일반적으로 연속적인 메모리 공간에 저장되며, strides를 통해 각 차원의 데이터 간 간격을 결정 

id와 __ array_interface __

- id()
    - 파이썬 자체의 고유 메모리 주소 반환
    - 객체의 컨테이너 또는 참조 수준에서 메모리 주소 확인 
    - 객체의 내부 데이터가 아닌 객체 자체에 대한 정보 제공
    - 객체가 같은 데이터를 공유하더라도 다른 ID를 가질 수 있음 (Numpy 배열에서 뷰(view)와 원본 배열의 경우)
    - arr과 view_arr의 id는 다름. 이는 배열의 메타데이터와 배열 객체가 독립적으로 존재하기 때문 

- __ array_interface __
    - Numpy 배열 객체가 관리하는 실제 데이터 버퍼의 정보 제공 
    - 데이터 버퍼 주소를 확인하는 데 유용하며, 원본 배열과 뷰(view)간에 데이터 공유 여부를 판단할 수 있음 
        - 두 배열의 데이터 버퍼 주소가 같다면, 같은 메모리를 참조하고 있음을 의미 
    - Numpy 배열의 내부 구조를 설명하는 속성 (attribute) -> 이 속성을 통해 배열의 데이터 버퍼 주소, dtype, strides 등을 알 수 있음 
    - 딕셔너리 형태이며 주요키는 아래와 같음
        - data: 배열이 참조하는 데이터 버퍼의 메모리 주소와 읽기/쓰기 플래그 반환
            - 읽기 쓰기 플래그: False(읽기 전용), True(읽기 쓰기 모두 가능) -> 하지만 객체수준에서만 적용됨 (데이터 버퍼는 해당 안 됨)
        - shape: 배열의 형태
        - strides: 데이터가 메모리에서 이동하는 간격 (바이트단위)
        - typestr: 배열의 데이터 타입 (dtype)
        - version: 인터페이스 버전 
    

## 6.1 reshape

In [77]:
import numpy as np

a = np.arange(12)

print(id(a))
print(a.__array_interface__)
a

4447949840
{'data': (4486001008, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (12,), 'version': 3}


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
print(id(a.reshape(3, 4))) # a와 객체 자체의 메모리 주소는 다름 
print(a.reshape(3, 4).__array_interface__['data'][0]) # 데이터 자체는 같은 메모리 주소 참조

a.reshape(3, 4) 


4447952816
4497579232


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
print(id(a))
print(a.__array_interface__)

a # 여전히 a는 그대로인 걸 확인할 수 있음 

4447949840
{'data': (4486001008, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (12,), 'version': 3}


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [83]:
a_re_34 = a.reshape(3, 4)

# 배열 확인
print(a)
print(a_re_34)


# 각 객체의 id 확인 
print(id(a_re_34))
print(id(a))
print()

# reshape 객체의 base 확인 -> a를 가리킴 
print(a_re_34.base)

# 데이터 범퍼 주소 확인 
print(a.__array_interface__['data'][0])
print(a_re_34.__array_interface__['data'][0])



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4447593136
4447949840

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4486001008
4486001008


In [87]:
# -1을 활용한 배열 변경

a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [89]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [90]:
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
a.reshape(-1, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

## 6.2 배열크기변경 실습 01

[문제] \
1부터 40가지의 짝수를 갖는 ndarray를 arange()로 만듭니다.\
그리고 shape을 변경하여 (2, 2, 5)로 변경해보세요.\
\
[2 4 6 8 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40] \
\
[결과] \
array([[[2, 4, 6, 8, 10], \
    [12, 14, 16, 18, 20], \
\
    [[22, 24, 26, 28, 30], \
    [32, 34, 36, 38, 40]]])



In [93]:
a = np.arange(2, 41, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [95]:
a.reshape(2, 2, 5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

## 6.3 flatten, ravel

### 6.3.1 flatten
- 깊은 복사

In [10]:
import numpy as np
# (3, 4) 2차원 배열 생성

a = np.array([[0, 1, 2, 3],
	[4, 5, 6, 7],
	[8, 9, 10, 11]])
print(a.shape)
a

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
# flatten ((3, 4)차원을 1차원으로 변경)

# 변경
a_flatten = a.flatten()

# 크기 확인
print(a_flatten.shape)

# 배열 출력 
a_flatten

(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
# 변경 전후의 요소 0의 id와 버퍼 확인 (첫 요소의 id, 버퍼 주소가 다름)

# a의 첫 번째 요소 id 
print(a[0][0])
print(id(a[0][0])) # id
print(a.__array_interface__['data'])
print()

# flatten 후의 첫 번째 소요 id 확인 
print(a_flatten[0])
print(id(a_flatten[0])) # id 다름 
print(a_flatten.__array_interface__['data']) # 버퍼 주소가 다름 

0
4591420368
(5484219488, False)

0
4591420368
(4947842800, False)


In [13]:
# 요소 변경 -> 두 객체 다 변경되지 않는것을 알 수 있음 

# 요소 변경 
print(a_flatten[0])
a_flatten[0] = 100
print()

# 변경된 array 확인 
print(a)
print()
print(a_flatten)

0

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[100   1   2   3   4   5   6   7   8   9  10  11]


### 6.3.2 ravel
- 깊은 복사

In [14]:
# (3, 4) 2차원 배열 생성

a = np.array([[0, 1, 2, 3],
	[4, 5, 6, 7],
	[8, 9, 10, 11]])
print(a.shape)
a

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
# ravel

# ravel로 평탄화 
a_ravel = a.ravel()

# 크기 확인
print(a_ravel.shape)

# ravel 출력 
a_ravel

(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:


print(a.__array_interface__['data'])
a

(5216320848, False)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
# a, a_ravel, a.ravel() id 확인 -> id 주소가 모두 다름 
print(id(a))
print(id(a_ravel))
print(id(a.ravel()))

print()

# 각 객체의 요소 0의 id 확인 -> id 주소가 모두 다름
print(id(a[0][0]))
print(id(a_ravel[0]))
print(id(a.ravel()[0]))
print()

# 각 객체의 데이터 버퍼 주소 확인 -> 버퍼 주소가 같음
print(a.__array_interface__['data'])
print(a_ravel.__array_interface__['data'])


4591401744
4591402608
4591389456

4591421136
4591420848
4591421008

(5216320848, False)
(5216320848, False)


In [18]:
# a의 요소 0을 100으로 바꿔보기 

# 변경 전 값 확인
print(a[0][0])
print(a_ravel[0])
print(a.__array_interface__['data'])
print(a_ravel.__array_interface__['data'])
print()

# 요소 변경
a_ravel[0] = 100 
print()

# 변경 후 값 확인
print(a)
print(a_ravel) # a_ravel도 값이 변경돼있는 걸 알 수 있음 

0
0
(5216320848, False)
(5216320848, False)


[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[100   1   2   3   4   5   6   7   8   9  10  11]


In [19]:
# 0번째 인덱스 id값 확인 
print(id(a[0][0]))
print(id(a_ravel[0]))

# 0번째 인덱스 버퍼 주소 확인
print(a.__array_interface__['data'])
print(a_ravel.__array_interface__['data'])

4591420880
4591420624
(5216320848, False)
(5216320848, False)


---
예제

In [46]:
import numpy as np

# 원본 배열 생성
arr = np.array([[1, 2], [3, 4]])

# arr의 뷰(view) 생성
view_arr = arr.ravel()

# 뷰를 수정하면 원본 배열도 변경됨
view_arr[0] = 99

print(arr)      # [[99  2]
                #  [ 3  4]]
print(view_arr) # [99  2  3  4]
print()

print(id(arr))
print(id(view_arr))
print(id(arr[0][0]))
print(id(view_arr[0]))
print()

# 실제 데이터 주소 비교
print(arr.__array_interface__)
print("Data buffer address of arr:", arr.__array_interface__['data'][0])
print("Data buffer address of view_arr:", view_arr.__array_interface__['data'][0])



[[99  2]
 [ 3  4]]
[99  2  3  4]

4443249552
4443253104
4442170640
4442173104

{'data': (5559721088, False), 'strides': None, 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (2, 2), 'version': 3}
Data buffer address of arr: 5559721088
Data buffer address of view_arr: 5559721088


## 6.4 newaxis
- 인덱싱 기법으로 배열의 차원을 늘리는 데 유용

In [108]:
# 1차원 배열 생성
a = np.arange(12)

# 크기 확인
print(a.shape, a.ndim)

a

(12,) 1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# 차원 증가 
a = a[:, np.newaxis] # 새로운 축 추가 -> 모든 행 유지하면서 새로운 열 차원 추가  

# 크기 확인 
print(a.shape, a.ndim) 

a

(12, 1) 2


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [114]:
a = np.arange(12) 
print(a.shape)
print()

# 차원 증가 
a = a[np.newaxis, :] # 행에 새로운 축 추가 
print(a.shape)
a

(12,)

(1, 12)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

## 6.5 전치 

In [ ]:
# 배열 생성
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.shape)
a

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
b = a.T

print(b.shape)
b

(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [119]:
print(id(a))
print(id(a.T))
print(a.__array_interface__['data'])
print(a.T.__array_interface__['data'])


4442993264
4448947344
(4497526352, False)
(4497526352, False)


## 6.6 배열 결합

### 6.6.1 hstack
배열을 수평으로 연결 

In [124]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10, 20, 30], [40, 50, 60]])
print(a.shape, b.shape)
print(a)
print(b)

(2, 3) (2, 3)
[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]


In [ ]:
# hstack 

c_hstack = np.hstack([a, b])

print(c_hstack.shape) # 같은 행 끼리 요소 연결 
c_hstack

(2, 6)


array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

### 6.6.2 vstack
배열을 수직으로 연결 

In [126]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10, 20, 30], [40, 50, 60]])
print(a.shape, b.shape)
print(a)
print(b)

(2, 3) (2, 3)
[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]


In [ ]:
# vstack 

c_vstack = np.vstack([a, b])

print(c_vstack.shape) # 같은 열 끼리 연결 (수직 연결)
c_vstack

(4, 3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

# 7. 브로드캐스팅

In [ ]:
import numpy as np 
# 예제 1

a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

print(a.shape, b.shape) # 차원은 다르지만 차원의 크기가 동일 (열크기 == 행크기)

(3,) (3, 1)


In [134]:
result = a + b # a가 (1, 3)으로 자동 확장되어 b와 연산 가능해짐 
print(result.shape)
result

(3, 3)


array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
# 곱셈
c = b*a
print(c)
c.shape 

[[10 20 30]
 [20 40 60]
 [30 60 90]]


(3, 3)

In [ ]:
# 예제 2

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print(a.shape, b.shape) # 차원은 다르지만 차원의 크기는 동일 (열 크기 == 행 크기)

(2, 3) (3,)


In [ ]:
result = a * b # b가 자동으로 브로드캐스트 되어 a의 각 행에 대해 요소별로 곱셈이 이루어짐 

print(result.shape)
result

(2, 3)


array([[ 10,  40,  90],
       [ 40, 100, 180]])

# 8. NumPy의 다양한 메서드 

In [137]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.shape)
a

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

## 8.1 최대/최소

In [ ]:
# 최대
print(a.max())

# 최소
print(a.min())

# 최대값 인덱스 
print(a.argmax())

# 최소값 인덱스
print(a.argmin())

6
1
5
0


## 8.1.1 argmax, argmin
- argmax: 해당 배열의 제일 큰 값의 인덱스 반환
- argmin: 해당 배열의 제일 작은 값의 인덱스 반환 

In [ ]:
arr = np.reshape(np.random.randint(100, size=(12)), (2, 3, -1)) # 0에서 99사이의 정수 24개 생성
display(arr)
print()

print(np.argmax(arr)) # 축을 설정하지 않으면 1차원으로 생각했을 때의 인덱스 값을 반환함
print(np.argmin(arr))
print()

# 확인 
print(arr.flatten()[np.argmax(arr)]) # 1차원으로 축소 후 인덱싱을 통해 값 확인 
print(arr.flatten()[np.argmin(arr)]) 

array([[[16,  5],
        [62, 23],
        [75, 44]],

       [[42, 56],
        [37, 63],
        [66, 93]]])


11
1

93
5


In [ ]:
# 축을 설정 했을 경우 (axis 설정 햇을 경우)
np.random.seed(1) # 랜덤값의 재현성 보장

arr = np.reshape(np.random.randint(100, size=(24)), (2, 3, 2, -1)) 
print(arr.shape)
arr

(2, 3, 2, 2)


array([[[[37, 12],
         [72,  9]],

        [[75,  5],
         [79, 64]],

        [[16,  1],
         [76, 71]]],


       [[[ 6, 25],
         [50, 20]],

        [[18, 84],
         [11, 28]],

        [[29, 14],
         [50, 68]]]])

In [ ]:
# 첫 번째 축에 대해 각 위치에서 두 개의 값 중 최댓값이 있는 첫 번째 축의 인덱스 반환
# 즉, arr[0][i][j][k]와 arr[1][i][j][k]를 비교하여 두 개의 (3, 2, 2)를 비교했을 때 더 큰 값이 존재하는 배열의 인덱스를 반환
# 그 결과도 결국 (3, 2, 2)가 됨
print(np.argmax(arr, axis=0)) 
print('-'*10)

# 두 번째 축(크기3)을 따라 최소값의 인덱스 반환 (2, 2, 2)
print(np.argmin(arr, axis=1))
print('-'*10)

# 세 번째 축(크기3)을 따라 최소값의 인덱스 반환 (2, 3, 2)
print(np.argmin(arr, axis=2))

[[[0 1]
  [0 1]]

 [[0 1]
  [0 0]]

 [[1 1]
  [0 0]]]
----------
[[[2 2]
  [0 0]]

 [[0 2]
  [1 0]]]
----------
[[[0 1]
  [0 0]
  [0 0]]

 [[0 1]
  [1 1]
  [0 0]]]


## 8.2 통계

In [149]:
print('---합---')
print(a.sum())
print(np.sum(a))
print()

print('---평균---')
print(a.mean())
print(np.mean(a))
print()

print('---중의값---') 
print(np.median(a))
print()

print('---표준편차---') 
print(a.std())
print(np.std(a))
print()

print('---분산---') 
print(a.var())
print(np.var(a))

---합---
21
21

---평균---
3.5
3.5

---중의값---
3.5

---표준편차---
1.707825127659933
1.707825127659933

---분산---
2.9166666666666665
2.9166666666666665


## 8.3 불리언

### 8.3.1 all()

In [ ]:
# 넘파이의 all() 메서드는 and와 동일한 논리를 가짐 

a = np.array([True, True, True])
b = np.array([True, True, False])
c = np.array([False, False, False])

print(a.dtype)
print(a.all())
print(b.all())
print(c.all())

bool
True
False
False


In [161]:
a = np.zeros(3, dtype=int)
b = np.ones(3, dtype=int)
c = np.array([1, 1, 0])

print(a)
print(b)
print(c)
print()

print(a.all())
print(b.all())
print(c.all())

[0 0 0]
[1 1 1]
[1 1 0]

False
True
False


In [154]:
b = a.all()

print(b)

False


### 8.3.2 any()

In [ ]:
# 넘파이의 any() 메서드는 or과 동일한 논리를 가짐 

a = np.array([True, True, True])
b = np.array([True, True, False])
c = np.array([False, False, False])

print(a.dtype)
print(a.any())
print(b.any())
print(c.any())


bool
True
True
False


In [162]:
a = np.zeros(3, dtype=int)
b = np.ones(3, dtype=int)
c = np.array([1, 1, 0])

print(a)
print(b)
print(c)
print()

print(a.any())
print(b.any())
print(c.any())

[0 0 0]
[1 1 1]
[1 1 0]

False
True
True


## 8.4 NumPy의 다양한 메서드 실습 01

[문제] 1부터 100까지의 3의 배수를 갖는 1차원 ndarray를 생성하고 그 전체의 합을 구하세요

In [163]:
a = np.arange(3, 101, 3)
print(a.sum())

1683


## 8.5 NumPy의 다양한 메서드 실습 02

[문제] 
- 서버 응답시간의 데이터가 다음과 같이 존재합니다.
- 해당 값의 단위는 ms 입니다.
- 이 때 200ms를 넘기는 값의 개수가 총 몇개인지 구해보세요


In [164]:
resp_time = np. array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119,  4, 102,
177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
199, 55, 151, 183, 152, 119, 193, 110, 204])

In [165]:
resp_time > 200 

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True])

In [166]:
result = np.sum(resp_time > 200)
print(result)

8


# 9. 정렬

In [184]:
np.random.seed(2)
arr = np.reshape(np.random.randint(20, size=12), (3, -1))
arr

array([[ 8, 15, 13,  8],
       [11, 18, 11,  8],
       [ 7,  2, 17, 11]])

In [ ]:
print(np.sort(arr, axis=0)) # 첫 번째 축 기준으로 오름차순 정렬 (원본의 각 행끼리 비교)
print()

print(np.sort(arr, axis=1))

[[ 7  2 11  8]
 [ 8 15 13  8]
 [11 18 17 11]]

[[ 8  8 13 15]
 [ 8 11 11 18]
 [ 2  7 11 17]]
