## 4.4 슬라이싱 실습 01

[문제] 주어진 행렬에 대하여 각 문제를 해결해보세요.
- 값 7 인덱싱
- 값 14 인덱싱
- 배열 [6, 7] 슬라이싱
- 배열 [7, 12] 슬라이싱
- 배열 [[3, 4], [8, 9]]


In [4]:
import numpy as np

m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [5]:
# 1. 7 인덱싱 
print(m[1, 2])

# 2. 14 인덱싱
print(m[2, -1])

# 3. [6, 7] 슬라이싱
print(m[1, 1:3])

# 4. [7, 12] 슬라이싱
print(m[1:, 2])

# 5. [[3, 4], [8, 9]] 슬라이싱 
print(m[:2, -2:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


## 4.5 슬라이싱 실습 02

[문제] 주어진 행렬에 대하여 각 문제를 해결해보세요.
\
\
array([[[  1,   2,   3], \
        [  4,   5,   6], \
        [  7,   8,   9]], \
 \
       [[ 10,  20,  30], \
        [ 40,  50,  60], \
        [ 70,  80,  90]], \
\
       [[100, 200, 300], \
        [400, 500, 600], \
        [700, 800, 900]]])
        

## 실습 02 배열 생성

In [6]:
# 방법 1
import numpy as np

# 배열 생성
a = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 20, 30], [40, 50, 60], [70, 80, 90]],
    [[100, 200, 300], [400, 500, 600], [700, 800, 900]]
])

a

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [7]:
# 방법 2
test = np.array([[i + j for i in range(1,4)] for j in range(3)])
print(test)
print()
test2 = test*10
print(test2)
print()
test3 = test*100
print(test3)
print()
a = np.array([test, test2, test3])
a

[[1 2 3]
 [2 3 4]
 [3 4 5]]

[[10 20 30]
 [20 30 40]
 [30 40 50]]

[[100 200 300]
 [200 300 400]
 [300 400 500]]



array([[[  1,   2,   3],
        [  2,   3,   4],
        [  3,   4,   5]],

       [[ 10,  20,  30],
        [ 20,  30,  40],
        [ 30,  40,  50]],

       [[100, 200, 300],
        [200, 300, 400],
        [300, 400, 500]]])

In [8]:
print(a.shape)
print(a.dtype)

(3, 3, 3)
int64


In [9]:
# 방법 3
import numpy as np

# arange로 배열 생성
a = np.arange(1, 10).reshape(3,3) * np.array([1, 10, 100]).reshape(3, 1, 1)

print(a)

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]


## 02-1

[문제 1] 아래와 같은 배열을 출력하세요
\
\
array([[2, 5, 8], \
    [20, 50, 80], \
    [200, 500, 800]])


In [10]:
result = a[:, :, 1]
print(result)

[[  2   5   8]
 [ 20  50  80]
 [200 500 800]]


## 02-2

[문제 2] 아래와 같은 배열을 출력하세요
\
\
array([[1, 3], \
    [100, 300]])


In [11]:
result = a[::2, 0, ::2]
result

array([[  1,   3],
       [100, 300]])

## 02-3

[문제 2] 아래와 같은 배열을 출력하세요
\
\
array([[[3, 2, 1], \
    [9, 8, 7]], \
\
    [[30, 20, 10], \
    [90, 80, 70]]])


In [12]:
result = a[:2:, ::2, ::-1]
result

array([[[ 3,  2,  1],
        [ 9,  8,  7]],

       [[30, 20, 10],
        [90, 80, 70]]])

# 배열생성2 실습 01

[문제] 빈 문자열을 갖는 shape이 (3, 3, 3) ndarray를 만들어 봅시다.
- 단, dtype은 ‘U10’으로 합니다.


In [13]:
reuslt = np.zeros((3, 3, 3), dtype='<U10')
reuslt

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

# 배열생성2 실습 02
[문제] zeros/ones 함수를 사용해서 배열을 만들고 아래와 같은 배열을 만들어 보세요
\
\
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.], \
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
my_ones = np.ones((10, 10))
my_ones[1:9, 1:9] = my_ones[1:9, 1:9] * 0 # 10번째 인덱스가 9니깐 8번인덱스까지 0.이 나오게 해야함
my_ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
my_ones.shape

(10, 10)

# 배열생성2 실습 03
[문제] zeros/ones 함수를 사용해서 배열을 만들고 아래와 같은 배열을 만들어 보세요


In [16]:
my_ones = np.ones((10, 10))
my_ones[0::2, 1::2] = my_ones[0::2, 1::2] * 0 # 10번째 인덱스가 9니깐 8번인덱스까지 0.이 나오게 해야함
my_ones[1::2, 0::2] = my_ones[1::2, 0::2] * 0
my_ones

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])